name: msibi
channels:
- conda-forge
dependencies:
- freud=2.4.1
- gsd=2.4.1
- mbuild=0.10.13
- mdanalysis=1.0.1
- mdtraj=1.9.5
- numpy=1.20.1
- pip=21.0.1
- python=3.7
- pytest=6.2.2
- pytest-cov=2.11.1
